"""Burridge-Knopoff earthquake fault (Carlson & Langer 1989) — a faithful
mechanical spring-block reproduction.

Source: Carlson, J. M. & Langer, J. S. (1989), "Properties of earthquakes
generated by fault dynamics", Phys. Rev. Lett. 62(22):2632-2635.
doi:10.1103/PhysRevLett.62.2632. After Burridge, R. & Knopoff, L. (1967),
"Model and theoretical seismicity", Bull. Seismol. Soc. Am. 57(3):341-371.

FRAMING DISCLOSURE — genuine-agent (mechanical spring-block chain, disclosed).
Each block is a genuine MECHANICAL agent carrying continuous position u and
velocity v STATE and obeying Newton's law with inertia: it is pulled by a slow
loader plate, coupled to its two neighbours by leaf springs (stiffness ratio
ell), tied to the plate by a coil spring, and held by a velocity-WEAKENING
friction nonlinearity. We integrate the coupled equations of motion (inertia
included) with an energy-stable velocity-Verlet integrator on a small fixed
timestep. This is NOT a discrete threshold-redistribution cellular automaton:
unlike ``olami_feder_christensen`` (an instantaneous, inertia-free CA caricature
of B-K), here the inertia + friction nonlinearity produce the real slip-burst
dynamics. We build it on the neutral ``abm_auto._platform`` floor — each block is
a ``BlockAgent`` in the model's ``AgentSet`` roster — but the tick is a
model-level synchronous integration step (all blocks advance from one snapshot),
so the per-agent ``step`` is a no-op. We disclose the mechanical-agent framing so
the reproduction is neither over- nor under-claimed.

Mechanism (Carlson-Langer nondimensional form):

  * STATE — a 1D chain of N blocks with positions u[i] and velocities v[i]. The
    loader plate sits at position ``nu * t`` (slow loading rate nu). Fixed
    (zero-displacement, pinned) boundary blocks at each end (u=0), so the chain
    has N free interior blocks between two pins.
  * EQUATION OF MOTION (nondimensional; coil-spring stiffness = 1, inertia = 1):
        u_i'' = ell^2 * (u_{i+1} - 2 u_i + u_{i-1})   [leaf springs to neighbours]
                - (u_i - nu * t)                      [coil spring to the plate]
                - phi(v_i)                            [friction, velocity-weakening]
    ``ell`` is the stiffness ratio (leaf/coil); ``ell^2`` is the coupling
    coefficient in the common nondimensionalisation.
  * FRICTION LAW (velocity-weakening, the physical heart of B-K):
      - a block is STUCK (v = 0) until the total elastic force on it exceeds the
        static threshold F0 in magnitude; while stuck the friction exactly
        cancels the elastic force (the block does not move) and no motion is
        integrated.
      - once SLIPPING the kinetic friction drops with slip speed:
            phi(v) = F0 * (1 - sigma) / (1 + v / (1 - sigma)),   v > 0
        so phi(0+) = F0 (continuous with the static threshold) and phi decreases
        monotonically as v grows — velocity WEAKENING. ``sigma`` sets how sharply
        friction weakens. (For v < 0, phi(v) = -phi(-v), an odd law.)
  * EVENT (slip burst) — the chain alternates long STUCK loading intervals (all
    blocks below threshold; the plate drags them elastically) with brief SLIP
    bursts. A burst begins when at least one block first exceeds threshold; we
    then integrate the equations of motion until every block is stuck again
    (all |v| below a small tolerance). The event MOMENT is the total slip
    displacement summed over every block that moved during the burst:
        moment = sum_i (u_i(after) - u_i(before))   over participating blocks.
    A transient is discarded before events are collected.

Numerics — velocity-Verlet (symplectic, energy-stable) with a fixed micro-
timestep ``dt`` chosen small relative to the fastest oscillation period so slip
bursts are physical, not numerical. During long stuck intervals we do NOT
integrate step-by-step; we analytically jump the plate to the load at which the
next block reaches threshold (the stuck dynamics are just u_i fixed, plate
advancing), which keeps the run finite while leaving the slip dynamics fully
resolved. The measured quantities are the per-event moment series and, from it,
the MLE power-law exponent over the small-event region, the number of decades
the moments span, the max/median ratio, and the mean moment (all locked metrics,
see PREDICTIONS-locked.md). Determinism: the only randomness is the seeded
initial-position perturbation; the integration is otherwise deterministic.
"""
from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from abm_auto._platform import Agent, AgentModel


# -- friction law -------------------------------------------------------------

def friction_force(v: np.ndarray, F0: float, sigma: float,
                   alpha: float) -> np.ndarray:
    """Velocity-weakening kinetic friction (Carlson-Langer 1989).

    phi(v) = sign(v) * F0 * (1 - sigma) / (1 + 2*alpha*|v| / (1 - sigma))   (v != 0).

    The static friction threshold is the maximum F0 (= 1 in the standard
    nondimensionalisation). At the ONSET of slip (v -> 0+) the KINETIC branch
    starts at F0*(1 - sigma), i.e. a discontinuous drop of sigma*F0 below the
    static maximum: sigma sets the size of that static->kinetic drop. ``alpha``
    controls how fast the kinetic friction then WEAKENS with slip speed — larger
    alpha -> friction falls off faster with |v|. This velocity WEAKENING is the
    instability that makes a slipping block accelerate and drives the slip burst.
    The law is odd in v; for a stuck (v = 0) block friction is not this force but
    whatever static value (up to F0) balances the elastic load.
    """
    av = np.abs(v)
    mag = F0 * (1.0 - sigma) / (1.0 + 2.0 * alpha * av / (1.0 - sigma))
    return np.sign(v) * mag


# -- Agent --------------------------------------------------------------------

class BlockAgent(Agent):
    """One mechanical block: continuous position ``u`` and velocity ``v``.

    The Burridge-Knopoff tick (advance every block's Newtonian equation of motion
    from one snapshot) is a model-level synchronous integration, so the per-agent
    ``step`` is intentionally a no-op; the block simply carries its (u, v) state.
    """

    def __init__(self, agent_id: int, model: "BurridgeKnopoffModel", *,
                 u: float, v: float) -> None:
        super().__init__(agent_id, model)
        self.u = u
        self.v = v

    def step(self) -> None:  # pragma: no cover - the tick lives on the model
        return None


# -- Model --------------------------------------------------------------------

class BurridgeKnopoffModel(AgentModel):
    """A 1D Carlson-Langer spring-block chain of N free blocks between two pins.

    Construct with N, stiffness ratio ``ell``, friction (``F0``, ``sigma``),
    loader rate ``nu``, integrator step ``dt``, and a seed. ``collect_events``
    runs the stick-slip dynamics and returns the per-event moment series (after a
    transient). The velocity-Verlet integrator is symplectic / energy-stable;
    ``dt`` is validated against the fastest oscillation period.
    """

    def __init__(self, n: int = 64, *, ell: float = 3.0, F0: float = 1.0,
                 sigma: float = 0.01, alpha: float = 3.0, nu: float = 0.001,
                 dt: float = 0.02, seed: int = 0,
                 init_noise: float = 1e-3) -> None:
        super().__init__(seed=seed, schedule="sequential")
        if n <= 0:
            raise ValueError(f"need n > 0 (got {n})")
        if ell <= 0:
            raise ValueError(f"need ell > 0 (got {ell})")
        if F0 <= 0:
            raise ValueError(f"need F0 > 0 (got {F0})")
        if not (0.0 < sigma < 1.0):
            raise ValueError(f"need 0 < sigma < 1 (got {sigma})")
        if alpha <= 0:
            raise ValueError(f"need alpha > 0 (got {alpha})")
        if nu <= 0:
            raise ValueError(f"need nu > 0 (got {nu})")
        if dt <= 0:
            raise ValueError(f"need dt > 0 (got {dt})")

        # Energy-stable timestep guard. The stiffest linear restoring frequency of
        # a block is set by the coil spring (unit stiffness) plus the two leaf
        # springs: omega_max^2 <= 1 + 4*ell^2 (the +4*ell^2 is the k=pi lattice
        # mode of the coupling). velocity-Verlet is stable for dt*omega < 2; we
        # require a comfortable margin so slip bursts resolve the oscillation.
        omega_max = math.sqrt(1.0 + 4.0 * ell * ell)
        if dt * omega_max > 0.5:
            raise ValueError(
                f"dt={dt} too large for ell={ell}: dt*omega_max={dt*omega_max:.3f} "
                f"> 0.5 (velocity-Verlet needs dt*omega well under 2 for physical, "
                f"energy-stable slip bursts); reduce dt")

        self.seed_value = seed
        self.n = n
        self.ell = float(ell)
        self.ell2 = float(ell) ** 2
        self.F0 = float(F0)
        self.sigma = float(sigma)
        self.alpha = float(alpha)
        self.nu = float(nu)
        self.dt = float(dt)
        self.init_noise = float(init_noise)
        self.omega_max = omega_max

        # State arrays (positions u, velocities v) for the N free blocks. Fixed
        # pins at both ends contribute u=0 in the coupling stencil. A tiny seeded
        # position perturbation breaks the perfectly-uniform lattice so the first
        # instability is not perfectly synchronous.
        self.u = np.zeros(n, dtype=float)
        self.v = np.zeros(n, dtype=float)
        rng = np.random.default_rng(seed)
        self.u += init_noise * rng.standard_normal(n)

        # Loader-plate position L = nu * t. We track L directly (the "time" of the
        # slow loading) rather than integrating t; during stuck intervals L jumps.
        self.plate = 0.0

        self.agent_list: List[BlockAgent] = []
        for i in range(n):
            a = BlockAgent(i, self, u=float(self.u[i]), v=0.0)
            self.agent_list.append(a)
            self.add_agent(a)

    # -- forces ----------------------------------------------------------------

    def _coupling(self, u: np.ndarray) -> np.ndarray:
        """Leaf-spring (discrete Laplacian) coupling ell^2*(u_{i+1}-2u_i+u_{i-1})
        with fixed u=0 pins at both ends."""
        lap = np.empty_like(u)
        lap[1:-1] = u[2:] - 2.0 * u[1:-1] + u[:-2]
        lap[0] = u[1] - 2.0 * u[0]           # left pin u_{-1} = 0
        lap[-1] = u[-2] - 2.0 * u[-1]        # right pin u_{N} = 0
        return self.ell2 * lap

    def elastic_force(self, u: np.ndarray, plate: float) -> np.ndarray:
        """Total elastic (spring) force on each block, EXCLUDING friction:
        ell^2*Laplacian(u) - (u - plate). This is the force the static friction
        must balance to keep a block stuck."""
        return self._coupling(u) - (u - plate)

    def acceleration(self, u: np.ndarray, v: np.ndarray, plate: float,
                     moving: Optional[np.ndarray] = None,
                     slip_dir: Optional[np.ndarray] = None) -> np.ndarray:
        """Newtonian acceleration (unit mass) of the MOVING (slipping) blocks:
        elastic force minus velocity-weakening kinetic friction.

        For a slipping block the kinetic friction OPPOSES its slip direction and
        starts (at slip onset, |v| -> 0+) at the reduced kinetic value
        F0*(1 - sigma) — a discontinuous drop of sigma*F0 below the static
        maximum F0 — then weakens further as |v| grows. That onset stress drop is
        the physical instability: the moment a block breaks free the friction
        holding it falls below the elastic load, leaving a net unbalanced force
        ~ sigma*F0 that accelerates the block and can push its neighbours over
        threshold (the slip cascade). We therefore apply friction along the fixed
        per-block SLIP DIRECTION (set when the block un-sticks), NOT along
        sign(v) — otherwise a block sitting exactly at v = 0 would feel zero
        friction and sigma would have no effect.

        A block that is STUCK (not in ``moving``) has its acceleration forced to
        zero: static friction holds it in place (it does not move), so its
        equation of motion is inert until the elastic load exceeds F0. When
        ``moving`` is None every block is treated as slipping with friction along
        sign(v) (used by tests that exercise the raw odd force law)."""
        elastic = self.elastic_force(u, plate)
        if slip_dir is None:
            fric = friction_force(v, self.F0, self.sigma, self.alpha)
        else:
            # Kinetic friction magnitude at |v|, applied opposite the slip
            # direction (onset value F0*(1-sigma), weakening with speed).
            av = np.abs(v)
            mag = self.F0 * (1.0 - self.sigma) / (
                1.0 + 2.0 * self.alpha * av / (1.0 - self.sigma))
            fric = slip_dir * mag
        acc = elastic - fric
        if moving is not None:
            acc = np.where(moving, acc, 0.0)
        return acc

    # -- stuck-interval loading -----------------------------------------------

    def _load_to_next_threshold(self) -> bool:
        """Advance the (stuck) plate to the load at which the next block first
        reaches the static friction threshold F0.

        While every block is stuck (v = 0), each u_i is fixed and the plate
        advances; the elastic force on block i is E_i(L) = coupling_i - (u_i - L),
        which grows linearly in the plate position L (slope +1 per block). Block i
        reaches threshold when |E_i(L)| = F0. We jump the plate to the SMALLEST
        future L at which any block crosses +F0 (blocks are dragged in the +
        direction by the advancing plate, so the first crossing is the +F0 one),
        then release that burst. Returns True if a next event exists.
        """
        coupling = self._coupling(self.u)
        # E_i(L) = coupling_i - u_i + L. Solve coupling_i - u_i + L = +F0 for L.
        L_hit = self.F0 - (coupling - self.u)
        future = L_hit[L_hit > self.plate + 1e-15]
        if future.size == 0:
            return False
        self.plate = float(np.min(future))
        return True

    # -- slip burst ------------------------------------------------------------

    def _run_burst(self, max_micro: int = 2_000_000) -> Tuple[float, int]:
        """Integrate the equations of motion (velocity-Verlet) through one slip
        burst, holding the plate FIXED, until all blocks are stuck again.

        Stick-slip bookkeeping (Carlson-Langer, exactly): each block carries a
        ``stuck`` flag.
          * A STUCK block has v = 0 and does not move; static friction holds it.
            It UN-STICKS (joins the slip) the moment the elastic load on it
            exceeds the static threshold, |elastic| > F0.
          * A SLIPPING block integrates u_i'' = elastic - phi(v_i). It RE-STICKS
            the instant its velocity returns to zero (crosses sign): at that
            zero-crossing v is clamped to 0 and the block freezes. This is the
            physical stop condition — a slipping block decelerates under friction
            + springs and re-locks when it momentarily stops; it only re-slips if
            the (now static) load again tops F0.
        The burst ends when no block is slipping. Returns (event moment, number of
        blocks that participated) where the moment is the total forward slip
        summed over participating blocks.
        """
        u = self.u.copy()
        v = self.v.copy()
        plate = self.plate
        dt = self.dt
        u_start = u.copy()

        # Per-block SLIP DIRECTION (+1 / -1), set the moment a block un-sticks and
        # held fixed while it slips: the block breaks in the direction the elastic
        # load pushes it, and kinetic friction opposes that direction (with the
        # onset stress drop to F0*(1-sigma)). Zero while stuck.
        slip_dir = np.zeros_like(u)

        # Seed the slip: any block AT OR ABOVE the static threshold un-sticks (the
        # block that loading brought exactly to F0 must break free). It breaks in
        # the direction the elastic load pushes it.
        elastic = self.elastic_force(u, plate)
        moving = np.abs(elastic) >= self.F0
        slip_dir[moving] = np.sign(elastic[moving])
        v[~moving] = 0.0
        a = self.acceleration(u, v, plate, moving, slip_dir)

        micro = 0
        while micro < max_micro and np.any(moving):
            v_prev = v.copy()
            # velocity-Verlet half-kick / drift / kick, applied only to movers
            # (stuck blocks have a = 0 and v = 0, so they neither drift nor kick).
            v_half = v + 0.5 * dt * a
            u = u + dt * v_half
            a_new = self.acceleration(u, v_half, plate, moving, slip_dir)
            v = v_half + 0.5 * dt * a_new
            micro += 1

            # RE-STICK: a slipping block stops when its velocity reverses against
            # its slip direction (it has slid forward, decelerated under friction
            # + springs, and momentarily halted). Detect v * slip_dir <= 0 for a
            # mover that has actually started moving (v_prev along slip_dir > 0),
            # clamp its velocity to zero and drop it from the mover set. Its slip
            # direction is cleared; it can re-slip later only if the static load
            # again tops F0.
            reversed_ = moving & (v * slip_dir <= 0.0) & (v_prev * slip_dir > 0.0)
            if np.any(reversed_):
                v[reversed_] = 0.0
                moving = moving & ~reversed_
                slip_dir[reversed_] = 0.0

            # UN-STICK: a stuck block whose static elastic load now tops F0 joins
            # the slip (the cascade — a slipping neighbour redistributes force and
            # can push it over). It breaks in the elastic-load direction.
            elastic = self.elastic_force(u, plate)
            newly = (~moving) & (np.abs(elastic) >= self.F0)
            if np.any(newly):
                slip_dir[newly] = np.sign(elastic[newly])
                moving = moving | newly

            # Keep stuck blocks pinned (guard against any residual velocity) and
            # recompute the accelerations for the current mover set.
            v[~moving] = 0.0
            a = self.acceleration(u, v, plate, moving, slip_dir)

        self.u = u
        self.v = v
        slip = u - u_start
        # Event moment = total forward slip over blocks that participated (moved
        # by more than a micro-step's worth of the plate rate — a real slip, not
        # numerical drift).
        eps = max(self.nu, 1e-12) * dt
        participated = np.abs(slip) > eps
        moment = float(np.sum(slip[participated]))
        return moment, int(np.count_nonzero(participated))

    # -- event collection ------------------------------------------------------

    def collect_events(self, n_events: int, *, transient: int = 200,
                       max_micro: int = 2_000_000) -> Dict[str, Any]:
        """Run the stick-slip dynamics and collect ``n_events`` slip-burst moments
        AFTER discarding the first ``transient`` events.

        Each cycle: load the plate to the next threshold crossing, then integrate
        the slip burst to completion. Returns the collected moment series plus the
        per-event participating-block counts, and syncs the agent roster state.
        """
        if n_events <= 0:
            raise ValueError(f"need n_events > 0 (got {n_events})")
        if transient < 0:
            raise ValueError(f"need transient >= 0 (got {transient})")

        moments: List[float] = []
        sizes: List[int] = []
        total = n_events + transient
        collected = 0
        for _ in range(total):
            if not self._load_to_next_threshold():
                break
            moment, size = self._run_burst(max_micro=max_micro)
            collected += 1
            if collected > transient:
                moments.append(moment)
                sizes.append(size)
            if len(moments) >= n_events:
                break

        # Sync the agent roster with the final state (keeps the platform roster
        # consistent for inspection / tests).
        for i, ag in enumerate(self.agent_list):
            ag.u = float(self.u[i])
            ag.v = float(self.v[i])

        moms = np.asarray(moments, dtype=float)
        return {
            "n": self.n,
            "ell": self.ell,
            "F0": self.F0,
            "sigma": self.sigma,
            "alpha": self.alpha,
            "nu": self.nu,
            "dt": self.dt,
            "seed": self.seed_value,
            "n_events": len(moments),
            "transient": transient,
            "moments": moments,
            "sizes": sizes,
            "mean_moment": float(np.mean(moms)) if moms.size else 0.0,
            "median_moment": float(np.median(moms)) if moms.size else 0.0,
            "max_moment": float(np.max(moms)) if moms.size else 0.0,
            "min_moment": float(np.min(moms)) if moms.size else 0.0,
        }


# -- power-law / heavy-tail metrics -------------------------------------------

def positive_moments(moments: Sequence[float]) -> np.ndarray:
    """The strictly-positive event moments (drop any numerical zeros/negatives)."""
    m = np.asarray(list(moments), dtype=float)
    return m[m > 0.0]


def mle_power_law_exponent(moments: Sequence[float], *,
                           xmin: Optional[float] = None,
                           xmax: Optional[float] = None) -> Dict[str, Any]:
    """Continuous-MLE power-law exponent (Clauset-Shalizi-Newman) for the event
    moments in the scaling window [xmin, xmax].

    For a continuous power law p(x) ~ x^{-alpha} on x >= xmin, the MLE is
        alpha = 1 + n / sum_i ln(x_i / xmin).
    We restrict to the small-event scaling region [xmin, xmax] (the
    Gutenberg-Richter region); if xmin/xmax are None they default to the min/max
    of the positive moments. Returns alpha, the standard error, and the count in
    the window.
    """
    x = positive_moments(moments)
    if x.size == 0:
        return {"alpha": float("nan"), "stderr": float("nan"), "n_in_window": 0,
                "xmin": float("nan"), "xmax": float("nan")}
    lo = float(np.min(x)) if xmin is None else float(xmin)
    hi = float(np.max(x)) if xmax is None else float(xmax)
    win = x[(x >= lo) & (x <= hi)]
    n = win.size
    if n < 2 or lo <= 0.0:
        return {"alpha": float("nan"), "stderr": float("nan"), "n_in_window": int(n),
                "xmin": lo, "xmax": hi}
    s = float(np.sum(np.log(win / lo)))
    if s <= 0.0:
        return {"alpha": float("nan"), "stderr": float("nan"), "n_in_window": int(n),
                "xmin": lo, "xmax": hi}
    alpha = 1.0 + n / s
    stderr = (alpha - 1.0) / math.sqrt(n)
    return {"alpha": float(alpha), "stderr": float(stderr), "n_in_window": int(n),
            "xmin": lo, "xmax": hi}


def decades_spanned(moments: Sequence[float]) -> float:
    """log10(max/min) of the strictly-positive event moments — how many decades of
    scale the moment distribution covers."""
    x = positive_moments(moments)
    if x.size == 0:
        return 0.0
    lo, hi = float(np.min(x)), float(np.max(x))
    if lo <= 0.0:
        return 0.0
    return math.log10(hi / lo)


def max_over_median(moments: Sequence[float]) -> float:
    """max / median over the strictly-positive event moments (a heavy-tail ratio:
    how far the largest event dwarfs the typical one)."""
    x = positive_moments(moments)
    if x.size == 0:
        return 0.0
    med = float(np.median(x))
    if med <= 0.0:
        return float("inf")
    return float(np.max(x)) / med


def small_event_window(moments: Sequence[float], *,
                       lo_pct: float = 50.0, hi_pct: float = 97.5) -> Tuple[float, float]:
    """A robust small-event scaling window [xmin, xmax] from percentiles of the
    positive moments.

    The GR / power-law scaling region is the SMALL-event body of the distribution
    (large characteristic events sit above it). We take xmin at the ``lo_pct``
    percentile (drop the smallest single-block events dominated by discreteness)
    and xmax at the ``hi_pct`` percentile (cut the extreme characteristic tail),
    fixed BEFORE looking at the fitted exponent. Returns (xmin, xmax).
    """
    x = positive_moments(moments)
    if x.size == 0:
        return (float("nan"), float("nan"))
    lo = float(np.percentile(x, lo_pct))
    hi = float(np.percentile(x, hi_pct))
    if hi <= lo:
        hi = float(np.max(x))
    return (lo, hi)


# -- experiment helpers -------------------------------------------------------

def run_single(n: int = 64, *, ell: float = 3.0, F0: float = 1.0,
               sigma: float = 0.01, alpha: float = 3.0, nu: float = 0.001,
               dt: float = 0.02, seed: int = 0, n_events: int = 4000,
               transient: int = 200, init_noise: float = 1e-3) -> Dict[str, Any]:
    """One Burridge-Knopoff run: collect ``n_events`` slip-burst moments at a
    given (ell, seed) and attach the locked scaling / heavy-tail metrics."""
    model = BurridgeKnopoffModel(
        n, ell=ell, F0=F0, sigma=sigma, alpha=alpha, nu=nu, dt=dt, seed=seed,
        init_noise=init_noise)
    res = model.collect_events(n_events, transient=transient)
    moments = res["moments"]
    lo, hi = small_event_window(moments)
    fit = mle_power_law_exponent(moments, xmin=lo, xmax=hi)
    res["mle_alpha"] = fit["alpha"]
    res["mle_stderr"] = fit["stderr"]
    res["mle_n_in_window"] = fit["n_in_window"]
    res["mle_xmin"] = fit["xmin"]
    res["mle_xmax"] = fit["xmax"]
    res["decades"] = decades_spanned(moments)
    res["max_over_median"] = max_over_median(moments)
    return res


def run_many_seeds(n: int = 64, *, ell: float = 3.0, F0: float = 1.0,
                   sigma: float = 0.01, alpha: float = 3.0, nu: float = 0.001,
                   dt: float = 0.02, n_seeds: int = 3, seed_base: int = 0,
                   n_events: int = 4000, transient: int = 200,
                   init_noise: float = 1e-3) -> Dict[str, Any]:
    """Run ``n_seeds`` Burridge-Knopoff runs at fixed parameters (seed
    ``seed_base + i``) and POOL their moments, then compute the locked metrics on
    the pooled series (more events -> a cleaner scaling fit).

    Returns the pooled metrics plus per-seed mean moments (for the ell sweep in
    P3) and one representative moment series for inspection.
    """
    runs = [run_single(n, ell=ell, F0=F0, sigma=sigma, alpha=alpha, nu=nu, dt=dt,
                       seed=seed_base + i, n_events=n_events, transient=transient,
                       init_noise=init_noise)
            for i in range(n_seeds)]
    pooled: List[float] = []
    for r in runs:
        pooled.extend(r["moments"])
    per_seed_mean = [r["mean_moment"] for r in runs]

    lo, hi = small_event_window(pooled)
    fit = mle_power_law_exponent(pooled, xmin=lo, xmax=hi)
    pos = positive_moments(pooled)
    mean_moment = float(np.mean(pos)) if pos.size else 0.0
    return {
        "n": n,
        "ell": ell,
        "F0": F0,
        "sigma": sigma,
        "alpha": alpha,
        "nu": nu,
        "dt": dt,
        "n_seeds": n_seeds,
        "seed_base": seed_base,
        "n_events": n_events,
        "transient": transient,
        "n_pooled_events": len(pooled),
        "n_positive_events": int(pos.size),
        "mle_alpha": fit["alpha"],
        "mle_stderr": fit["stderr"],
        "mle_n_in_window": fit["n_in_window"],
        "mle_xmin": fit["xmin"],
        "mle_xmax": fit["xmax"],
        "decades": decades_spanned(pooled),
        "max_over_median": max_over_median(pooled),
        "mean_moment": mean_moment,
        "median_moment": float(np.median(pos)) if pos.size else 0.0,
        "max_moment": float(np.max(pos)) if pos.size else 0.0,
        "per_seed_mean_moment": per_seed_mean,
        "example_moments": runs[0]["moments"][:2000],
    }
